#Example configuration for autogitpull
General : root : repos include - private : true show - skipped : false show -
                                                                 version
    : false interval : 30 refresh -
      rate : 250ms cli : false single - run : false single -
                                            repo : false silent : false recursive
    : false max -
      depth : 0 row - order : default color : "" no - colors : false show - commit -
                                                               date : false show - commit -
                                                                      author : false vmem
    : false updated -
      since : "" auto - config : false auto - reload - config : false rerun - last : false save -
                                                                                     args
    : false enable -
      history : false session - dates -
                only : false Logging : log - dir : logs log - file : autogitpull.log log -
                                                   level : INFO verbose
    : false debug -
      memory : false dump - state : false dump - large : 0 syslog : false syslog -
                                                                    facility : 1 Concurrency
    : concurrency : 4 single -
      thread : false max -
               threads : 8 Tracking : cpu - poll : 5 mem - poll : 5 thread - poll : 5 no - cpu -
                                      tracker : false no - mem - tracker : false no - thread -
                                                                           tracker
    : false net -
      tracker : false Resource limits : cpu - percent : 50 cpu - cores : 0xff mem -
                                        limit : 0 download - limit : 0 upload - limit : 0 disk -
                                        limit : 0 Actions : check - only : false no - hash -
                                                                           check
    : false force -
      pull : false discard - dirty : false remove - lock : false kill -
                                                           all : false

#Per - repository overrides
                                                                 repos /
                                                                 example : force -
                                                           pull : true pull - timeout : 30
