#ifndef AUTOGITPULL_VERSION_HPP
#define AUTOGITPULL_VERSION_HPP

#define AUTOGITPULL_VERSION_MAJOR 1
#define AUTOGITPULL_VERSION_MINOR 0
#define AUTOGITPULL_VERSION_PATCH 0

#define AUTOGITPULL_VERSION_STR "1.0.0"
#define AUTOGITPULL_VERSION_RC                                                                     \
    AUTOGITPULL_VERSION_MAJOR, AUTOGITPULL_VERSION_MINOR, AUTOGITPULL_VERSION_PATCH, 0

constexpr const char* AUTOGITPULL_VERSION = AUTOGITPULL_VERSION_STR;

#endif // AUTOGITPULL_VERSION_HPP
