import libs = libgit2%lib{git2} yaml-cpp%lib{yaml-cpp} nlohmann-json%lib{nlohmann_json}
using rc


lib_sources = git_utils logger resource_utils system_utils time_utils \
              config_utils debug_utils scanner ui_loop options parse_utils \
              lock_utils process_monitor linux_daemon windows_service tui \
              help_text

lib{autogitpull}: cxx{$lib_sources} $libs

rc{icon}: ../graphics/icon.rc
rc{version}: version.rc

exe{autogitpull}: cxx{autogitpull} lib{autogitpull} rc{icon} rc{version}
