name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up build environment
        uses: aminya/setup-cpp@v1

      - name: Install dependencies
        run: ./scripts/install_deps.sh

      - name: Lint
        run: b lint

      - name: Test
        run: b test
