name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up build environment
        uses: aminya/setup-cpp@v1

      - name: Install dependencies
        run: ./scripts/install_deps.sh

      - name: Install clang-format
        run: sudo apt-get update && sudo apt-get install -y clang-format

      - name: Auto Format
        run: make format && git diff --exit-code

  lint:
    needs: format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up build environment
        uses: aminya/setup-cpp@v1

      - name: Install dependencies
        run: ./scripts/install_deps.sh

      - name: Install clang-format
        run: sudo apt-get update && sudo apt-get install -y clang-format

      - name: Auto Lint
        run: make lint

  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up build environment
        uses: aminya/setup-cpp@v1

      - name: Install dependencies
        run: ./scripts/install_deps.sh

      - name: Auto Test
        run: make test

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up build environment
        uses: aminya/setup-cpp@v1

      - name: Install dependencies
        run: ./scripts/install_deps.sh

      - name: Auto Build
        run: make
