---
name: Release

on:
  push:
    tags:
      - 'v*'
      - '*/release'
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up C++ build environment
        uses: aminya/setup-cpp@v1

      - name: Install dependencies (Windows)
        if: runner.os == 'Windows'
        shell: powershell
        run: scripts/install_deps.bat
      - name: Install dependencies (*nix)
        if: runner.os != 'Windows'
        shell: bash
        run: ./scripts/install_deps.sh
      - name: Install lint tools
        run: pip install cpplint
      - name: Install clang-format
        shell: bash
        run: |
          if [ "$RUNNER_OS" = "Linux" ]; then
            sudo apt-get update && sudo apt-get install -y clang-format
          elif [ "$RUNNER_OS" = "macOS" ]; then
            brew install clang-format
          elif [ "$RUNNER_OS" = "Windows" ]; then
            choco install -y llvm
          fi

      - name: Lint
        run: make lint

      - name: Test
        run: ctest --test-dir build -C Release -R autogitpull_tests --output-on-failure || true

      - name: Configure (Windows)
        if: runner.os == 'Windows'
        shell: powershell
        run: cmake -S . -B build -G "Visual Studio 17 2022" -DCMAKE_BUILD_TYPE=Release
      - name: Configure (*nix)
        if: runner.os != 'Windows'
        shell: bash
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
      - name: Build
        shell: bash
        run: cmake --build build --config Release -j

      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: autogitpull-${{ matrix.os }}
          path: |
            build/Release/autogitpull.exe
            build/autogitpull
