name: Rolling Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-test-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check recent releases
        id: check_releases
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          SINCE=$(date -u -d '24 hours ago' +'%Y-%m-%dT%H:%M:%SZ')
          COUNT=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/repos/${{ github.repository }}/releases?per_page=100" \
            | jq "[.[] | select(.created_at >= \"$SINCE\")] | length")
          echo "releases_last24h=$COUNT" >> "$GITHUB_OUTPUT"
          if [ "$COUNT" -ge 2 ]; then
            echo "skip_build=true" >> "$GITHUB_OUTPUT"
          else
            echo "skip_build=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Skip build when release limit reached
        if: steps.check_releases.outputs.skip_build == 'true'
        run: echo 'Skipping build: daily release threshold reached.'

      - name: Set up C++ build environment
        if: steps.check_releases.outputs.skip_build != 'true'
        uses: aminya/setup-cpp@v1

      - name: Install dependencies
        if: steps.check_releases.outputs.skip_build != 'true'
        run: ./scripts/install_deps.sh

      - name: Install lint tools
        if: steps.check_releases.outputs.skip_build != 'true'
        run: pip install cpplint

      - name: Lint
        if: steps.check_releases.outputs.skip_build != 'true'
        run: b lint

      - name: Build
        if: steps.check_releases.outputs.skip_build != 'true'
        run: |
          mkdir build && cd build
          cmake ..
          make -j$(nproc)

      - name: Run Tests
        if: steps.check_releases.outputs.skip_build != 'true'
        run: |
          cd build
          ctest

      - name: Get next rolling tag
        if: steps.check_releases.outputs.skip_build != 'true'
        id: rolling_tag
        run: |
          TODAY=$(date +'%Y.%m.%d')
          git fetch --tags
          LAST=$(git tag --list "${TODAY}-*" | grep -E "^${TODAY}-[0-9]+$" | sed "s/^${TODAY}-//" | sort -n | tail -1)
          if [ -z "$LAST" ]; then
            NEXT="${TODAY}-1"
          else
            NEXT_NUM=$((LAST + 1))
            NEXT="${TODAY}-${NEXT_NUM}"
          fi
          echo "NEXT_TAG=$NEXT" >> $GITHUB_ENV
          echo "Rolling tag: $NEXT"

      - name: Tag commit
        if: steps.check_releases.outputs.skip_build != 'true'
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git tag $NEXT_TAG
          git push origin $NEXT_TAG

      - name: Create GitHub Release
        if: steps.check_releases.outputs.skip_build != 'true'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.NEXT_TAG }}
          name: Rolling Release ${{ env.NEXT_TAG }}
          body: "Automated rolling release for ${{ env.NEXT_TAG }}"
          draft: false
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Asset
        if: steps.check_releases.outputs.skip_build != 'true'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.NEXT_TAG }}
          files: build/autogitpull
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
